#!/bin/bash>school
echo "The school is open!">>school
cd ..
git add .
git commit -m My personal work
git push --set-upstream origin update_script
git checkout main
cd bash
echo #!/bin/bash
ALX School is so cool
